### ISSUE TITLE
クエリパラメータも受けるようにする

### ISSUE THREAD

**Issue by Tosuke** [future-link/misskey-auth#15]
今のままでは[仕様違反](https://tools.ietf.org/html/rfc6749#section-3.1)

**Comment by otofune** [comment]
含んでも良いでは

**Comment by otofune** [comment]
`The endpoint URI MAY include an "application/x-www-form-urlencoded" formatted (per Appendix B) query component ([RFC3986] Section 3.4),` なので

**Comment by Tosuke** [comment]
GETがMUSTなのでやっぱりできるようにしないと死

**Comment by otofune** [comment]
たし蟹
