### ISSUE TITLE
GETリクエスト以外でbodyがJSONであるかを確認する

### ISSUE THREAD

**Issue by otofune** [future-link/misskey-auth#17]
`ctx.request.body` が文字列になったりしなかったりしそうで厳しい気持ちになりそうなので

**Comment by Tosuke** [comment]
koa-bodyparserがapplication/jsonとapplication/x-www-urlencodedしか受け付けないはずなんですが

**Comment by otofune** [comment]
note: そもそもkoaはボディーをパースしないのでこれは見当違いだったけど、パースできなかったらから空のオブジェクトになるので〜というのにtosukeが気がついてくれた
