### ISSUE TITLE
APIでのjws.infoUrlになるべきエンドポイントの査定と作成

### ISSUE THREAD

**Issue by otofune** [future-link/misskey-auth#21]

**Comment by otofune** [comment]
@tosuke APIのPRで仮想で実装した分の実装どういうの想定してますか。

**Comment by Tosuke** [comment]
@otofune
{
key: 公開鍵(pen),
algorithm: 署名アルゴリズム
}

**Comment by otofune** [comment]
@tosuke え、penってpemですか

**Comment by Tosuke** [comment]
typoなのでpemです

**Comment by Tosuke** [comment]
jwkだとalgorithm含むので、標準規格に乗っかった方が幸せになれるかも

**Comment by otofune** [comment]
jwkを返すエンドポイント、どこにするかという感じでは有るが

**Comment by Tosuke** [comment]
googleがやってるので参考にしていきたい

**Comment by otofune** [comment]
良さそう、だけれどどうにしたって単体しか飛ばさないなら /cert や /pubkey とかでも良いかもしれない。PRだと /cert になってるみたいだけど

**Comment by Tosuke** [comment]
#34
