### ISSUE TITLE
ドキュメントを書く

### ISSUE THREAD

**Issue by otofune** [future-link/misskey-auth#22]
`/tokens/create` 系がない。ドキュメントがあるとはまやかしだったのだ

**Comment by Tosuke** [comment]
古いので

**Comment by otofune** [comment]
古いドキュメント辛くて、更新してほしい・・・

**Comment by Tosuke** [comment]
書いたので、よさそう

**Comment by otofune** [comment]
そうだ、ドキュメントに対してのリンクとかが存在しないのでどこかで追加しないといけないな
