### ISSUE TITLE
何の意図があるのかわからないコードが有る

### ISSUE THREAD

**Issue by otofune** [future-link/misskey-auth#8]
箇所: https://github.com/future-link/misskey-auth/blob/master/src/endpoints/tokens/create.ts#L43-L46
既に直前の https://github.com/future-link/misskey-auth/blob/master/src/endpoints/tokens/create.ts#L36 で返り値が決定するか、もしくはエラーがthrowされるかでここにはどうやってもたどり着かないのでは

**Comment by Tosuke** [comment]
Authorizationヘッダ以外の方法でidとsecretが渡された場合の処理

**Comment by Tosuke** [comment]
気になるならelseに包むといい

**Comment by otofune** [comment]
あー `if (ctx.header.authorization !== undefined) {` のブロックかあ。了解
